name: Tasmota Device Manager
version: '2022.2.0'
slug: tdm
description: GUI application to discover and monitor devices flashed with Tasmota
arch:
  - amd64
url: https://github.com/ikifar2012/tasmota-device-manager-addon
startup: application
boot: auto
services:
  - mqtt:want
init: false
ingress: true
panel_icon: mdi:application-cog
ingress_entry: novnc/vnc_lite.html?resize=scale
image: ikifar/tdm-ha-addon
map:
  - share:rw
ports:
  5900/tcp:
ports_description:
  5900/tcp: TDM via VNC (Not required for Ingress. Not secure!)
options:
  debug: false
schema:
  debug: bool