name: Tasmota Device Manager
version: '2023.8.0'
slug: tdm
description: GUI application to discover and monitor devices flashed with Tasmota
arch:
  - amd64
url: https://github.com/ikifar2012/tasmota-device-manager-addon
codenotary: cas@mathesonsteplock.ca
startup: application
boot: auto
services:
  - mqtt:want
init: false
ingress: true
homeassistant_api: true
hassio_role: homeassistant
panel_icon: mdi:application-cog
ingress_entry: novnc/vnc_lite.html?scale=true
image: ikifar/tdm-ha-addon
map:
  - share:rw
ports:
  5900/tcp:
ports_description:
  5900/tcp: TDM via VNC (Not required for Ingress. Not secure!)
options:
  debug: false
  timeout: 30
  display_resolution: 1920x1080
schema:
  debug: bool
  timeout: int
  display_resolution: str